-- Chapter 11 - Algebraic Datatypes
--
-- Data Declarations Review
-- Data and Type Constructors
-- Type Constructors and kinds
-- Data Contructors and values
-- What's a type and what's data?
--
-- data [] a = [] | a : [a]
--
-- data List a = EmptyList | Cons a (List a)
--
